require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*
Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*
Metrics/CyclomaticComplexity:
  Exclude:
    - db/migrate/**/*
Metrics/PerceivedComplexity:
  Exclude:
    - db/migrate/**/*
Metrics/BlockLength:
  Exclude:
    - app/admin/**/*
    - spec/**/*
    - config/environments/**/*
RSpec/EmptyLineAfterSubject:
  Exclude:
    - spec/factories/**/*
