require:
  - rubocop-rails
  - rubocop-rspec
Layout/LineLength:
  Max: 120
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/Documentation:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*
Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*
Metrics/CyclomaticComplexity:
  Exclude:
    - db/migrate/**/*
Metrics/PerceivedComplexity:
  Exclude:
    - db/migrate/**/*
Metrics/BlockLength:
  Exclude:
    - app/admin/**/*
    - spec/**/*
    - config/environments/**/*
